/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2019-08-19T17:03:43.227+06:00
  3.26.0.2
  
  Standalone prediction code with sample test data for NaiveBayesModel named NaiveBayes_model_python_1566211537855_5

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/NaiveBayes_model_python_1566211537855_5 > NaiveBayes_model_python_1566211537855_5.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m NaiveBayes_model_python_1566211537855_5.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="NaiveBayes_model_python_1566211537855_5", algorithm="naivebayes")
public class NaiveBayes_model_python_1566211537855_5 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Multinomial; }
  public boolean isSupervised() { return true; }
  public int nfeatures() { return 6; }
  public int nclasses() { return 3; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_NaiveBayes_model_python_1566211537855_5.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 3;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* SepalLengthCm */ null,
    /* SepalWidthCm */ null,
    /* PetalLengthCm */ null,
    /* PetalWidthCm */ null,
    /* sepal_ratio */ null,
    /* petal_ratio */ null,
    /* Species */ NaiveBayes_model_python_1566211537855_5_ColInfo_6.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.34444444444444444,0.37777777777777777,0.2777777777777778};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public NaiveBayes_model_python_1566211537855_5() { super(NAMES,DOMAINS,"Species"); }
  public String getUUID() { return Long.toString(7227224214638613248L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double mean, sdev, prob;
    double[] nums = new double[3];
    for(int i = 0; i < 3; i++) {
      nums[i] = Math.log(NaiveBayes_model_python_1566211537855_5_APRIORI.VALUES[i]);
      for(int j = 0; j < 0; j++) {
        if(Double.isNaN(data[j])) continue;
        int level = (int)data[j];
        prob = level < 6 ? NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][level] : 0;
        nums[i] += Math.log(prob <= 0.0 ? 0.001 : prob);
      }
      for(int j = 0; j < data.length; j++) {
        if(Double.isNaN(data[j])) continue;
        mean = Double.isNaN(NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][0]) ? 0 : NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][0];
        sdev = Double.isNaN(NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][1]) ? 1 : (NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][1] <= 0.0 ? 0.001 : NaiveBayes_model_python_1566211537855_5_PCOND.VALUES[j][i][1]);
        prob = Math.exp(-((data[j]-mean)*(data[j]-mean))/(2.*sdev*sdev)) / (sdev*Math.sqrt(2.*Math.PI));
        nums[i] += Math.log(prob <= 0.0 ? 0.001 : prob);
      }
    }
    double sum;
    for(int i = 0; i < nums.length; i++) {
      sum = 0;
      for(int j = 0; j < nums.length; j++) {
        sum += Math.exp(nums[j]-nums[i]);
      }
      preds[i+1] = 1/sum;
    }
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.5);
    return preds;
  }
}
// Count of categorical levels in response.
class NaiveBayes_model_python_1566211537855_5_RESCNT implements java.io.Serializable {
  public static final int[] VALUES = new int[3];
  static {
    NaiveBayes_model_python_1566211537855_5_RESCNT_0.fill(VALUES);
  }
  static final class NaiveBayes_model_python_1566211537855_5_RESCNT_0 implements java.io.Serializable {
    static final void fill(int[] sa) {
      sa[0] = 31;
      sa[1] = 34;
      sa[2] = 25;
    }
  }
}
// Apriori class distribution of the response.
class NaiveBayes_model_python_1566211537855_5_APRIORI implements java.io.Serializable {
  public static final double[] VALUES = new double[3];
  static {
    NaiveBayes_model_python_1566211537855_5_APRIORI_0.fill(VALUES);
  }
  static final class NaiveBayes_model_python_1566211537855_5_APRIORI_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 0.34444444444444444;
      sa[1] = 0.37777777777777777;
      sa[2] = 0.2777777777777778;
    }
  }
}
// Conditional probability of predictors.
class NaiveBayes_model_python_1566211537855_5_PCOND implements java.io.Serializable {
  public static final double[][][] VALUES = new double[6][][];
  static {
    NaiveBayes_model_python_1566211537855_5_PCOND_0.fill(VALUES);
  }
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_0 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 5.0;
          sa[1] = 0.36787679096857323;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 5.944117647058824;
          sa[1] = 0.5052399228872679;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 6.636;
          sa[1] = 0.5337602458033011;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_0_0_2.VALUES;
      }
    }
}
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_1 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 3.383870967741935;
          sa[1] = 0.4050487824065592;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 2.8147058823529414;
          sa[1] = 0.3105541019973476;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 3.02;
          sa[1] = 0.25331140255951506;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_1_0_2.VALUES;
      }
    }
}
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_2 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 1.4483870967741934;
          sa[1] = 0.1877426744987864;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 4.3352941176470585;
          sa[1] = 0.44509607607128027;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 5.604;
          sa[1] = 0.4522904671410451;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_2_0_2.VALUES;
      }
    }
}
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_3 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 0.23225806451612907;
          sa[1] = 0.09447079539622659;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 1.352941176470588;
          sa[1] = 0.19883797899164807;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 2.1079999999999997;
          sa[1] = 0.24481285369305095;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_3_0_2.VALUES;
      }
    }
}
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_4 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 1.489502697158072;
          sa[1] = 0.13019637998079722;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 2.1276217409788667;
          sa[1] = 0.21350897940466884;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 2.209577360521197;
          sa[1] = 0.23786913911784177;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_4_0_2.VALUES;
      }
    }
}
  static class NaiveBayes_model_python_1566211537855_5_PCOND_0_5 implements java.io.Serializable {
    public static final double[][] VALUES = new double[3][];
    static {
      NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0.fill(VALUES);
    }
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_0 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_0_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_0_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 7.203763440860216;
          sa[1] = 3.027646407988233;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_1 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_1_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_1_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 3.2314887606626352;
          sa[1] = 0.2599504399099176;
        }
      }
}
    static class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_2 implements java.io.Serializable {
      public static final double[] VALUES = new double[2];
      static {
        NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_2_0.fill(VALUES);
      }
      static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_2_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 2.6878154866745256;
          sa[1] = 0.3404137616591041;
        }
      }
}
    static final class NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0 implements java.io.Serializable {
      static final void fill(double[][] sa) {
        sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_0.VALUES;
        sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_1.VALUES;
        sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_5_0_2.VALUES;
      }
    }
}
  static final class NaiveBayes_model_python_1566211537855_5_PCOND_0 implements java.io.Serializable {
    static final void fill(double[][][] sa) {
      sa[0] = NaiveBayes_model_python_1566211537855_5_PCOND_0_0.VALUES;
      sa[1] = NaiveBayes_model_python_1566211537855_5_PCOND_0_1.VALUES;
      sa[2] = NaiveBayes_model_python_1566211537855_5_PCOND_0_2.VALUES;
      sa[3] = NaiveBayes_model_python_1566211537855_5_PCOND_0_3.VALUES;
      sa[4] = NaiveBayes_model_python_1566211537855_5_PCOND_0_4.VALUES;
      sa[5] = NaiveBayes_model_python_1566211537855_5_PCOND_0_5.VALUES;
    }
  }
}
// Number of unique levels for each categorical predictor.
class NaiveBayes_model_python_1566211537855_5_DOMLEN implements java.io.Serializable {
  public static final double[] VALUES = null;
}
// The class representing training column names
class NamesHolder_NaiveBayes_model_python_1566211537855_5 implements java.io.Serializable {
  public static final String[] VALUES = new String[6];
  static {
    NamesHolder_NaiveBayes_model_python_1566211537855_5_0.fill(VALUES);
  }
  static final class NamesHolder_NaiveBayes_model_python_1566211537855_5_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "SepalLengthCm";
      sa[1] = "SepalWidthCm";
      sa[2] = "PetalLengthCm";
      sa[3] = "PetalWidthCm";
      sa[4] = "sepal_ratio";
      sa[5] = "petal_ratio";
    }
  }
}
// The class representing column Species
class NaiveBayes_model_python_1566211537855_5_ColInfo_6 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NaiveBayes_model_python_1566211537855_5_ColInfo_6_0.fill(VALUES);
  }
  static final class NaiveBayes_model_python_1566211537855_5_ColInfo_6_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Iris-setosa";
      sa[1] = "Iris-versicolor";
      sa[2] = "Iris-virginica";
    }
  }
}

